name: go test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    container: golang:1.22.5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download statictest binary
        uses: robinraju/release-downloader@v1.8
        with:
          repository: Yandex-Practicum/go-autotests
          latest: true
          fileName: statictest
          out-file-path: .tools
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup autotest binary
        run: |
          chmod -R +x $GITHUB_WORKSPACE/.tools/statictest
          mv $GITHUB_WORKSPACE/.tools/statictest /usr/local/bin/statictest

      - name: Run test
        run: make test
